21-May-2521:19:28 - INFO - La page d'accueil a été chargée.
21-May-2521:19:43 - WARNING - Not Found: /forms/
21-May-2521:20:36 - WARNING - Not Found: /accounts/login/
21-May-2521:21:09 - WARNING - Not Found: /accounts/login/
21-May-2521:21:25 - WARNING - Not Found: /update_dvd/
21-May-2521:38:37 - INFO - La page d'accueil a été chargée.
21-May-2521:38:37 - WARNING - Not Found: /favicon.ico
21-May-2521:39:32 - WARNING - Not Found: /forms/
21-May-2521:39:32 - WARNING - Not Found: /favicon.ico
21-May-2521:46:37 - INFO - La page d'accueil a été chargée.
21-May-2521:47:08 - INFO - La page d'accueil a été chargée.
21-May-2521:47:24 - INFO - La page d'accueil a été chargée.
21-May-2521:48:47 - INFO - La page d'accueil a été chargée.
21-May-2521:48:49 - INFO - La page biliothequaire est chargé
21-May-2521:49:19 - INFO - Le livre harry potteur a été ajouté
21-May-2521:49:19 - INFO - La page biliothequaire est chargé
21-May-2521:49:28 - ERROR - Internal Server Error: /emprunt/1/
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'emprunteur'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Gestion_Mediatheque\gestion_mediatheque\views.py", line 259, in emprunt
    emprunteur = Membre.objects.get(pk=request.POST['emprunteur'])
                                       ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'emprunteur'
21-May-2521:50:01 - ERROR - Internal Server Error: /emprunt/1/
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'emprunteur'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Gestion_Mediatheque\gestion_mediatheque\views.py", line 259, in emprunt
    emprunteur = Membre.objects.get(pk=request.POST['emprunteur'])
                                       ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'emprunteur'
21-May-2521:52:29 - INFO - La page d'accueil a été chargée.
21-May-2521:54:28 - INFO - La page d'accueil a été chargée.
21-May-2521:54:30 - INFO - La page biliothequaire est chargé
21-May-2521:54:40 - ERROR - Internal Server Error: /emprunt/1/
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'emprunteur'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\contrib\auth\decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Gestion_Mediatheque\gestion_mediatheque\views.py", line 259, in emprunt
    emprunteur = Membre.objects.get(pk=request.POST['emprunteur'])
                                       ~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'emprunteur'
21-May-2521:54:58 - INFO - La page biliothequaire est chargé
21-May-2521:55:01 - INFO - Utilisateur déconnecté
21-May-2521:55:01 - INFO - La page d'accueil a été chargée.
21-May-2521:55:16 - INFO - Utilisateur admin connecté
21-May-2521:55:16 - INFO - La page biliothequaire est chargé
21-May-2521:55:21 - INFO - Utilisateur déconnecté
21-May-2521:55:21 - INFO - La page d'accueil a été chargée.
21-May-2521:55:31 - ERROR - L'utilisateur n'a pas pus être connecté
21-May-2521:55:31 - INFO - La page d'accueil a été chargée.
21-May-2521:55:57 - ERROR - L'utilisateur n'a pas pus être connecté
21-May-2521:55:57 - INFO - La page d'accueil a été chargée.
21-May-2521:56:04 - WARNING - Not Found: /accounts/login/
22-May-2500:32:25 - INFO - La page d'accueil a été chargée.
22-May-2500:33:11 - WARNING - Not Found: /forms/
22-May-2500:33:16 - INFO - La page biliothequaire est chargé
22-May-2500:33:23 - INFO - Le livre harry potteur a été supprimé
22-May-2500:33:23 - INFO - La page biliothequaire est chargé
22-May-2500:33:37 - INFO - Le membre :  a été créé
22-May-2500:33:37 - INFO - La page biliothequaire est chargé
22-May-2500:33:51 - INFO - Le CD acdc a été ajouté
22-May-2500:33:51 - INFO - La page biliothequaire est chargé
22-May-2500:33:57 - INFO - Maxime a emprunté le media : acdc
22-May-2500:33:57 - INFO - La page biliothequaire est chargé
22-May-2500:34:36 - INFO - Le membre Maximea été supprimé.
22-May-2500:34:36 - INFO - La page biliothequaire est chargé
22-May-2513:20:33 - INFO - La page d'accueil a été chargée.
22-May-2513:20:40 - INFO - La page d'accueil a été chargée.
22-May-2513:20:42 - INFO - La page biliothequaire est chargé
22-May-2513:20:46 - INFO - La page d'accueil a été chargée.
22-May-2513:20:48 - INFO - La page biliothequaire est chargé
22-May-2513:20:49 - INFO - Utilisateur déconnecté
22-May-2513:20:49 - INFO - La page d'accueil a été chargée.
22-May-2513:20:59 - INFO - Utilisateur bibliothequaire connecté
22-May-2513:20:59 - INFO - La page biliothequaire est chargé
22-May-2513:21:07 - INFO - Le media acdc  a été rentré
22-May-2513:21:07 - INFO - La page biliothequaire est chargé
22-May-2513:21:24 - INFO - Le CD acdc a été supprimé
22-May-2513:21:24 - INFO - La page biliothequaire est chargé
22-May-2513:21:28 - INFO - Utilisateur déconnecté
22-May-2513:21:28 - INFO - La page d'accueil a été chargée.
22-May-2513:21:45 - INFO - Utilisateur bibliothequaire connecté
22-May-2513:21:45 - INFO - La page biliothequaire est chargé
22-May-2513:22:48 - INFO - Utilisateur déconnecté
22-May-2513:22:48 - INFO - La page d'accueil a été chargée.
22-May-2513:23:00 - INFO - Utilisateur bibliothequaire connecté
22-May-2513:23:00 - INFO - La page biliothequaire est chargé
22-May-2513:23:16 - INFO - Le membre :  a été créé
22-May-2513:23:16 - INFO - La page biliothequaire est chargé
22-May-2513:23:27 - INFO - Le membre John Doe a été modifié.
22-May-2513:23:27 - INFO - La page biliothequaire est chargé
22-May-2513:23:37 - INFO - Le membre John Doe a été modifié.
22-May-2513:23:37 - INFO - La page biliothequaire est chargé
23-May-2515:43:33 - INFO - La page d'accueil a été chargée.
23-May-2515:43:33 - WARNING - Not Found: /favicon.ico
23-May-2515:43:38 - INFO - La page biliothequaire est chargé
23-May-2515:43:38 - WARNING - Not Found: /favicon.ico
23-May-2515:54:11 - INFO - La page d'accueil a été chargée.
23-May-2515:54:11 - WARNING - Not Found: /favicon.ico
23-May-2515:54:14 - INFO - La page biliothequaire est chargé
26-May-2513:39:14 - INFO - La page d'accueil a été chargée.
26-May-2513:39:15 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: gestion_mediatheque_livre

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\gestion_mediatheque\gestion_mediatheque\views.py", line 23, in accueil
    return render(request, 'accueil.html',
                  {'livres': livres,
                   'cds': cds,
                   'dvds': dvds,
                   'jeuxplateux': jeuxplateux})
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: gestion_mediatheque_livre
26-May-2513:39:15 - WARNING - Not Found: /favicon.ico
26-May-2513:39:32 - INFO - La page d'accueil a été chargée.
26-May-2513:39:32 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: gestion_mediatheque_livre

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\gestion_mediatheque\gestion_mediatheque\views.py", line 23, in accueil
    return render(request, 'accueil.html',
                  {'livres': livres,
                   'cds': cds,
                   'dvds': dvds,
                   'jeuxplateux': jeuxplateux})
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: gestion_mediatheque_livre
26-May-2513:39:35 - INFO - La page d'accueil a été chargée.
26-May-2513:39:35 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: gestion_mediatheque_livre

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\gestion_mediatheque\gestion_mediatheque\views.py", line 23, in accueil
    return render(request, 'accueil.html',
                  {'livres': livres,
                   'cds': cds,
                   'dvds': dvds,
                   'jeuxplateux': jeuxplateux})
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: gestion_mediatheque_livre
26-May-2513:39:51 - INFO - La page d'accueil a été chargée.
26-May-2513:39:51 - ERROR - Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: gestion_mediatheque_livre

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\gestion_mediatheque\gestion_mediatheque\views.py", line 23, in accueil
    return render(request, 'accueil.html',
                  {'livres': livres,
                   'cds': cds,
                   'dvds': dvds,
                   'jeuxplateux': jeuxplateux})
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\template\defaulttags.py", line 199, in render
    len_values = len(values)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 366, in __len__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\hanon\Desktop\Gestion_Mediatheque\Lib\site-packages\django\db\backends\sqlite3\base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: gestion_mediatheque_livre
26-May-2513:41:10 - INFO - La page d'accueil a été chargée.
26-May-2513:41:19 - INFO - Utilisateur bibliothequaire connecté
26-May-2513:41:19 - INFO - La page biliothequaire est chargé
26-May-2513:41:39 - WARNING - Not Found: /favicon.ico
